### ISSUE TITLE
<SCHEMA_NAME_1> and <SCHEMA_NAME_2> in MTAEXT file?  Get table size Failed & Generate Data Failed

### ISSUE THREAD

**Issue by jmalla** [SAP/hana-shine-xsa#33] opened 2018-02-07 20:48 UTC
We are trying to build and run the code for SHINE - just downloaded the code from GitHub.  We have HANA XSA 2.0 SPS 2 with the latest build for HANA Express download.  The build is working fine.  The run works intermittently.

We are having issues connecting to the database and running the data generator.  

When we try to run the data generator, we get the error - "Get table size Failed".
we get an error stating "Generate Data Failed"

Unexpected error occured during Purchase order data generation.Please check the logs for more details
Unexpected error occured during sales order data generation.Please check the logs for more details

We have followed all of the steps in [https://github.com/SAP/hana-shine-xsa/blob/master/SHINE-XSA.md](url) but we think there are some steps missing that are needed to point to the correct database hdi container or there is an issue with permissions.

We see the following in the shine.mtaext.  Do we need to replace <SCHEMA_NAME_1> and <SCHEMA_NAME_2> in this file?  

`_schema-version: "3.1.0"
ID: XSAC_SHINE-CONFIG1
extends: XSAC_SHINE

modules:
  - name: di-local-npm-registry
    properties:
      UPSTREAM_LINK: "http://registry.npmjs.org"
      SAPUPSTREAM_LINK: "https://npm.sap.com"
       
resources:
          
  - name: shine-user-container
    parameters:
      config:
        schema: <SCHEMA_NAME_1>

  - name: shine-container
    parameters:
      config:
        schema: <SCHEMA_NAME_2>
`

We did see the following in the YAML file:
 parameters:
      service-name: shine-user-container
      config:
        schema: HANAUSER_SHINE_USER_SCHEMA

`_schema-version: 2.0.0
ID: com.sap.refapps.shine
version: 1.4.2
modules:
  - name: shine-web
    type: html5
    path: web
    provides:
      - name: web
        properties:
          ui-url: '${default-url}'
    requires:
      - name: shine-uaa
      - name: sapui5-provider
        properties:
          sapui5url: '~{url}'
      - name: core-js
        group: destinations
        properties:
          name: core-backend
          url: '~{url}'
          forwardAuthToken: true
      - name: user-js
        group: destinations
        properties:
          name: user-backend
          url: '~{url}'
          forwardAuthToken: true
      - name: user-java
        group: destinations
        properties:
          name: user-java-backend
          url: '~{url}'
          forwardAuthToken: true
      - name: uaa
        group: destinations
        properties:
          name: uaa
          url: '~{url}'
          forwardAuthToken: true
    parameters:
      host: web
      register-service-url: true
      service-name: web
      service-url: '${default-url}'
  - name: shine-core-js
    type: nodejs
    path: core-js
    provides:
      - name: core-js
        properties:
          url: '${default-url}'
    requires:
      - name: shine-uaa
      - name: shine-container
      - name: shine-core-db
      - name: shine-auditlog
  - name: shine-user-js
    type: nodejs
    path: user-js
    properties:
      SAP_JWT_TRUST_ACL: '[{"clientid":"*","identityzone":"*"}]'
    provides:
      - name: user-js
        properties:
          url: '${default-url}'
    requires:
      - name: shine-uaa
      - name: shine-scheduler
      - name: shine-user-db
      - name: shine-user-container
  - name: shine-user-java
    type: java
    path: user-java
    provides:
      - name: user-java
        properties:
          url: '${default-url}'
    requires:
      - name: shine-uaa
      - name: shine-scheduler
      - name: shine-user-db
      - name: shine-user-container
        properties:
          JBP_CONFIG_RESOURCE_CONFIGURATION: '[tomcat/webapps/ROOT/META-INF/context.xml: {"service_name_for_DefaultDB" : "~{user-container-name}"}]'
  - name: shine-core-db
    type: hdb
    path: core-db
    requires:
      - name: shine-container
        properties:
          TARGET_CONTAINER: '~{container-name}'
      - name: shine-user-container
        group: SERVICE_REPLACEMENTS
        properties:
          key: hdi-user-service
          service: '~{user-container-name}'
  - name: shine-user-db
    type: hdb
    path: user-db
    requires:
      - name: shine-user-container
        properties:
          TARGET_CONTAINER: '~{user-container-name}'
  - name: shine-site-web
    type: siteentry
    path: site-web
    parameters:
      memory: 64M
    requires:
      - name: shine-uaa
      - name: sap-portal-services-host
      - name: user-js
        group: destinations
        properties:
          name: user-backend
          url: '~{url}'
          forwardAuthToken: true
      - name: controller
        group: destinations
        properties:
          name: controller
          url: '~{url}'
      - name: user-java
        group: destinations
        properties:
          name: user-java-backend
          url: '~{url}'
          forwardAuthToken: true
      - name: core-js
        group: destinations
        properties:
          name: core-backend
          url: '~{url}'
          forwardAuthToken: true
      - name: uaa
        group: destinations
        properties:
          name: uaa
          url: '~{url}'
          forwardAuthToken: true
      - name: sapui5-provider
        properties:
          sapui5url: '~{url}'
    properties:
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
  - name: shine-site-content
    type: sitecontent
    path: site-content
    parameters:
      memory: 64M
    requires:
      - name: sap-portal-services-client
      - name: shine-uaa
    properties:
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
resources:
  - name: shine-auditlog
    type: com.sap.xs.auditlog
  - name: shine-container
    type: com.sap.xs.hdi-container
    properties:
      container-name: '${service-name}'
    parameters:
      service-name: shine-container
  - name: shine-user-container
    type: com.sap.xs.hdi-container
    properties:
      user-container-name: '${service-name}'
    parameters:
      service-name: shine-user-container
      config:
        schema: HANAUSER_SHINE_USER_SCHEMA
  - name: shine-scheduler
    type: com.sap.xs.job-scheduler
  - name: shine-uaa
    type: com.sap.xs.uaa-space
    parameters:
      config:
        xsappname: shine-admin
        scopes:
          - name: $XSAPPNAME.JOBSCHEDULER
            description: Job Scheduler Scope
            grant-as-authority-to-apps:
              - jobscheduler
          - name: $XSAPPNAME.Display
            description: display
          - name: $XSAPPNAME.Edit
            description: edit
          - name: $XSAPPNAME.Delete
            description: delete
          - name: $XSAPPNAME.DataGenerator
            description: data generator
          - name: xs_authorization.read
            description: Read authorization information from UAA
          - name: xs_authorization.write
            description: Write authorization information to UAA
        role-templates:
          - name: Admin
            description: refapps administrator
            scope-references:
              - $XSAPPNAME.Display
              - $XSAPPNAME.Edit
              - $XSAPPNAME.Delete
              - $XSAPPNAME.DataGenerator
              - $XSAPPNAME.JOBSCHEDULER
              - xs_controller.read
              - xs_authorization.read
              - xs_authorization.write
  - name: sap-portal-services-host
    type: com.sap.portal.site-host
    parameters:
      config:
        siteId: XSAC_SHINE
  - name: sap-portal-services-client
    type: com.sap.portal.site-content
    parameters:
      config:
        siteId: XSAC_SHINE
  - name: uaa
    properties:
      url: 'https://myIPonAWS.compute-1.amazonaws.com:39032/uaa-security'
  - name: sapui5-provider
    type: configuration
    parameters:
      provider-id: 'com.sap.ui5.dist.sapui5-dist-xsa.XSAC_UI5_FESV3:sapui5_fesv3'
      version: '>=1.44.8'
  - name: sap-portal-services-host-com.sap.refapps.shine
    parameters:
      config:
        siteId: com.sap.refapps.shine
    type: com.sap.portal.site-host
  - name: portal-uaa-com.sap.refapps.shine
    parameters:
      service-plan: space
    type: com.sap.xs.uaa
  - name: controller
    properties:
      url: 'https://myIPonAWS.compute-1.amazonaws.com:39030'
`

Your help is appreciated.

Thanks,
Jay

![shine data generation](https://user-images.githubusercontent.com/7725180/35944019-e736fc30-0c0f-11e8-92c8-2cb46283abd6.png)

**Comment by kiruthikan** [comment] 2018-02-09 04:53
Solved.

**Comment by kiruthikan** [comment] 2018-04-11 12:01
Hi,

Please give me more details on the issue.
Is SHINE installed in CF trial?
Is only the charts not loaded? Or you are not able to run the data generator itself?

Also, please execute the command "cf logs shine-core-js --recent" and share the output.
This will help me analyse the issue better.

Thanks and Regards,
Kiruthika

**Comment by panggou** [comment] 2018-04-12 05:46
@kiruthikan 

My problem is with the data generator itself.
Upon first login to "Data Generator", I get the error "Get table size Failed"
Generating Data PO 5*1000 failed as well.

the output of "cf logs shine-core-js --recent":
Retrieving logs for app shine-core-js in org IoT_XXX / space XXX as XXX...

   2018-04-12T13:40:44.92+0800 [APP/PROC/WEB/0] ERR Error: the predefined session variable cannot be set via SET command: XS_APPLICATIONUSER
   2018-04-12T13:40:44.94+0800 [RTR/4] OUT iot-XXX-XXX-shine-core-js.cfapps.eu10.hana.ondemand.com - [2018-04-12T05:40:44.905+0000] "GET /get/tablesize HTTP/1.1" 500 0 22 "https://iot-XXX-XXX-site-web.cfapps.eu10.hana.ondemand.com/sites" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "10.0.136.8:36432" "10.0.137.21:64384" x_forwarded_for:"169.145.206.234, 10.0.136.0, 52.28.241.88, 10.0.136.8" x_forwarded_proto:"https" vcap_request_id:"1bf5c70f-e2ab-4c5e-40ec-9ca72959dcbd" response_time:0.035098339 app_id:"5612584f-380f-4cc9-a597-a938053e1758" app_index:"0" x_b3_traceid:"d9d6ba528d9dccf7" x_b3_spanid:"d9d6ba528d9dccf7" x_b3_parentspanid:"-"
   2018-04-12T13:40:44.94+0800 [RTR/4] OUT
   2018-04-12T13:40:45.18+0800 [RTR/2] OUT iot-XXX-XXX-shine-core-js.cfapps.eu10.hana.ondemand.com - [2018-04-12T05:40:45.166+0000] "GET /get/tablesize HTTP/1.1" 500 0 22 "https://iot-XXX-XXX-site-web.cfapps.eu10.hana.ondemand.com/sites" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "10.0.136.8:56860" "10.0.137.21:64384" x_forwarded_for:"169.145.206.234, 10.0.136.0, 52.28.241.88, 10.0.136.8" x_forwarded_proto:"https" vcap_request_id:"b584fb97-0a5a-4a38-625e-c18e4529e8f3" response_time:0.019495287 app_id:"5612584f-380f-4cc9-a597-a938053e1758" app_index:"0" x_b3_traceid:"414872e68e386e67" x_b3_spanid:"414872e68e386e67" x_b3_parentspanid:"-"
   2018-04-12T13:40:45.18+0800 [RTR/2] OUT
   2018-04-12T13:40:45.18+0800 [APP/PROC/WEB/0] ERR Error: the predefined session variable cannot be set via SET command: XS_APPLICATIONUSER
   2018-04-12T13:40:45.70+0800 [APP/PROC/WEB/0] ERR Error: the predefined session variable cannot be set via SET command: XS_APPLICATIONUSER
   2018-04-12T13:40:45.70+0800 [RTR/6] OUT iot-XXX-XXX-shine-core-js.cfapps.eu10.hana.ondemand.com - [2018-04-12T05:40:45.684+0000] "GET /get/sessioninfo HTTP/1.1" 500 0 22 "https://iot-XXX-XXX-site-web.cfapps.eu10.hana.ondemand.com/sites" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "10.0.136.8:52840" "10.0.137.21:64384" x_forwarded_for:"169.145.206.234, 10.0.72.7, 52.28.241.88, 10.0.136.8" x_forwarded_proto:"https" vcap_request_id:"ec192906-295b-42d8-701d-807abb54e912" response_time:0.023388169 app_id:"5612584f-380f-4cc9-a597-a938053e1758" app_index:"0" x_b3_traceid:"f2422ddad12cbe81" x_b3_spanid:"f2422ddad12cbe81" x_b3_parentspanid:"-"
   2018-04-12T13:40:45.70+0800 [RTR/6] OUT
   2018-04-12T13:40:59.14+0800 [APP/PROC/WEB/0] ERR Error: the predefined session variable cannot be set via SET command: XS_APPLICATIONUSER
   2018-04-12T13:40:59.17+0800 [RTR/3] OUT iot-XXX-XXX-shine-core-js.cfapps.eu10.hana.ondemand.com - [2018-04-12T05:40:59.157+0000] "GET /replicate/sales HTTP/1.1" 500 0 22 "https://iot-XXX-XXX-site-web.cfapps.eu10.hana.ondemand.com/sites" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "10.0.136.8:37198" "10.0.137.21:64384" x_forwarded_for:"169.145.206.234, 10.0.72.7, 52.28.241.88, 10.0.136.8" x_forwarded_proto:"https" vcap_request_id:"d0eddc59-aed2-400d-475c-2cf7551ad969" response_time:0.017527384 app_id:"5612584f-380f-4cc9-a597-a938053e1758" app_index:"0" x_b3_traceid:"69e6e1f4f88183aa" x_b3_spanid:"69e6e1f4f88183aa" x_b3_parentspanid:"-"
   2018-04-12T13:40:59.17+0800 [RTR/3] OUT
   2018-04-12T13:40:59.46+0800 [RTR/2] OUT iot-XXX-XXX-shine-core-js.cfapps.eu10.hana.ondemand.com - [2018-04-12T05:40:59.441+0000] "GET /replicate/purchase HTTP/1.1" 500 0 22 "https://iot-XXX-XXX-site-web.cfapps.eu10.hana.ondemand.com/sites" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "10.0.136.8:59178" "10.0.137.21:64384" x_forwarded_for:"169.145.206.234, 10.0.72.7, 52.28.241.88, 10.0.136.8" x_forwarded_proto:"https" vcap_request_id:"d5dce31a-0411-49f9-60ab-38c8b57cbfe0" response_time:0.019180608 app_id:"5612584f-380f-4cc9-a597-a938053e1758" app_index:"0" x_b3_traceid:"b3e805de4ca7542e" x_b3_spanid:"b3e805de4ca7542e" x_b3_parentspanid:"-"
   2018-04-12T13:40:59.46+0800 [RTR/2] OUT
   2018-04-12T13:40:59.46+0800 [APP/PROC/WEB/0] ERR Error: the predefined session variable cannot be set via SET command: XS_APPLICATIONUSER


Thanks in advance!

**Comment by kiruthikan** [comment] 2018-04-13 10:43
Hi,
Thanks a lot for providing the logs.
We will look into this issue and see weather the same is reproducible in our systems and get back to you.

Thanks and Regards,
Kiruthika

**Comment by bbiswal333** [comment] 2019-04-24 06:14
Hi,

We could not able to reproduce this issue, so closing this issue. 
If you feel the issue still persists, please re-open the issue.

Thanks & Regards,
Bismay

**Closed by bbiswal333** 2019-04-24 06:14 UTC

**Comment by ahmedkhan29789** [comment] 2020-08-26 13:00
Do we anyone please where i can found my .mtaext file in HANA XSA, I checked everywhere in WEBIDE i am not able to find it
